
/*
 * This code was generated by Spiral 8.0.0, www.spiral.net
 */

double cospi(double x);
double sinpi(double x);

void init_DFT16(double a) {
}

void DFT16(long double  *Y, long double  *X) {
	float a = X[0] + 1;
	Y[0] = a;
}
