#include "igen_lib.h"
/*
 *             Automatically Tuned Linear Algebra Software v3.10.3
 * Copyright (C) 2011 R. Clint Whaley
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *   1. Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions, and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *   3. The name of the ATLAS group or the names of its contributers may
 *      not be used to endorse or promote products derived from this
 *      software without specific written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE ATLAS GROUP OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */
#include <igen_atlas_misc.h>
// #include <wmmintrin.h>
// #include <bmmintrin.h>
#include "igen_immintrin.h"
void ATL_dJIK56x56x56TN56x56x0_a1_b1(const int M, const int N, const int K,
                                     f64_I alpha, const f64_I *__restrict A,
                                     const int lda, const f64_I *__restrict B,
                                     const int ldb, f64_I beta,
                                     f64_I *__restrict C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=56,
 * lda=56, ldb=56, ldc=0, mu=4, nu=2, ku=1, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.39)
 */
{
  const int Mb = (M >> 2) << 2;
  const int Nb = (N >> 1) << 1;
  const f64_I *stM = A + (56 * (Mb));
  const f64_I *stN = B + (56 * (Nb));
  const f64_I *pfA = stM;
  const int incAm = 3 * 56;
  const int incAn = -(56 * (Mb));
  const int incBm = -56;
  const int incBn = 2 * 56;
  const int incCn = ((((ldc) << 1)) - (Mb));
  f64_I *pC0 = C;
  f64_I *pC1 = pC0 + (ldc);
  const f64_I *pA0 = A;
  const f64_I *pB0 = B;
  int k;
  m256di_2 rA0;
  m256di_2 rA1;
  m256di_2 rA2;
  m256di_2 rA3;
  m256di_2 rB0;
  m256di_2 rB1;
  m256di_2 t0;
  m256di_2 rC0_0;
  m256di_2 rC1_0;
  m256di_2 rC2_0;
  m256di_2 rC3_0;
  m256di_2 rC0_1;
  m256di_2 rC1_1;
  m256di_2 rC2_1;
  m256di_2 rC3_1;

  m256di_2 rc00;

  do /* N-loop */
  {
    do /* M-loop */
    {
      rC0_0 = _igen_mm256_setzero_pd();
      rC1_0 = _igen_mm256_setzero_pd();
      rC2_0 = _igen_mm256_setzero_pd();
      rC3_0 = _igen_mm256_setzero_pd();

      rc00 = _igen_mm256_loadu_pd(pC0);

      t0 = _igen_mm256_broadcast_sd(&beta);
      rc00 = _igen_mm256_mul_pd(rc00, t0);

      rC0_1 = _igen_mm256_setzero_pd();
      rC1_1 = _igen_mm256_setzero_pd();
      rC2_1 = _igen_mm256_setzero_pd();
      rC3_1 = _igen_mm256_setzero_pd();
      for (k = 0; k < 56; k += 4) /* easy loop to unroll */
      {
        rA0 = _igen_mm256_load_pd(pA0);
        rB0 = _igen_mm256_load_pd(pB0);
        rA1 = _igen_mm256_load_pd(pA0 + 56);
        rA2 = _igen_mm256_load_pd(pA0 + 2 * 56);
        rA3 = _igen_mm256_load_pd(pA0 + 3 * 56);
        rB1 = _igen_mm256_load_pd(pB0 + 56);

        t0 = _igen_mm256_mul_pd(rA0, rB0);
        rC0_0 = _igen_mm256_add_pd(rC0_0, t0);
        t0 = _igen_mm256_mul_pd(rA1, rB0);
        rC1_0 = _igen_mm256_add_pd(rC1_0, t0);
        t0 = _igen_mm256_mul_pd(rA2, rB0);
        rC2_0 = _igen_mm256_add_pd(rC2_0, t0);
        t0 = _igen_mm256_mul_pd(rA3, rB0);
        rC3_0 = _igen_mm256_add_pd(rC3_0, t0);
        t0 = _igen_mm256_mul_pd(rA0, rB1);
        rC0_1 = _igen_mm256_add_pd(rC0_1, t0);
        t0 = _igen_mm256_mul_pd(rA1, rB1);
        rC1_1 = _igen_mm256_add_pd(rC1_1, t0);
        t0 = _igen_mm256_mul_pd(rA2, rB1);
        rC2_1 = _igen_mm256_add_pd(rC2_1, t0);
        t0 = _igen_mm256_mul_pd(rA3, rB1);
        rC3_1 = _igen_mm256_add_pd(rC3_1, t0);

        pA0 += 4;
        pB0 += 4;
      }

      t0 = _igen_mm256_loadu_pd(pC1);

      rC0_0 = _igen_mm256_hadd_pd(rC0_0, rC1_0); /* c10cd c00cd c10ab c00ab */
      rC2_0 = _igen_mm256_hadd_pd(rC2_0, rC3_0); /* c30cd c20cd c30ab c20ab */

      rC3_0 = _igen_mm256_broadcast_sd(&beta);
      t0 = _igen_mm256_mul_pd(t0, rC3_0);

      rC1_0 = _igen_mm256_permute2f128_pd(rC0_0, rC2_0, 32);
      /* 0b 0 10 00 00 = 32 */ /* c30ab c20ab c10ab c00ab */
      rC0_0 = _igen_mm256_permute2f128_pd(rC0_0, rC2_0, 49);
      (__builtin_prefetch((void *)(pfA), ((1) >> 2) & 1, (1) & 3));
      /* 0b 0 11 00 01 = 1+16+32=97*/ /* c30cd c20cd c10cd c00cd */
      rC0_0 = _igen_mm256_add_pd(rC0_0, rC1_0);
      /* c30abcd c20abcd c10abcd c00abcd */
      rC0_0 = _igen_mm256_add_pd(rC0_0, rc00);

      _igen_mm256_storeu_pd(pC0, rC0_0);

      rC0_1 = _igen_mm256_hadd_pd(rC0_1, rC1_1); /* c11cd c01cd c11ab c01ab */
      rC2_1 = _igen_mm256_hadd_pd(rC2_1, rC3_1); /* c31cd c21cd c31ab c21ab */
      rC1_1 = _igen_mm256_permute2f128_pd(rC0_1, rC2_1, 32);
      /* 0b 0 10 00 00 = 32 */ /* c31ab c21ab c11ab c01ab */
      rC0_1 = _igen_mm256_permute2f128_pd(rC0_1, rC2_1, 49);
      /* 0b 0 11 00 01 = 1+16+32=97*/ /* c31cd c21cd c11cd c01cd */
      rC0_1 = _igen_mm256_add_pd(rC0_1, rC1_1);
      /* c31abcd c21abcd c11abcd c01abcd */
      rC0_1 = _igen_mm256_add_pd(rC0_1, t0);

      pfA += 8;
      _igen_mm256_storeu_pd(pC1, rC0_1);

      pC0 += 4;
      pC1 += 4;
      pA0 += incAm;
      pB0 += incBm;
    } while (pA0 != stM);
    pC0 += incCn;
    pC1 += incCn;
    pA0 += incAn;
    pB0 += incBn;
  } while (pB0 != stN);
}
